[config]
schemaVersion = "0.0.1"


[package]
namespace = "PonyWarrior"
name = "PonyAltar"
versionNumber = "0.4.2"
description = "Overhauls the Gods' keepsakes, transferring their functionality to an altar and giving each keepsake a unique effect."
websiteUrl = "https://github.com/PonyWarrior/PonyAltar"
containsNsfwContent = false

[package.dependencies]
SGG_Modding-DemonDaemon = "1.0.0"
SGG_Modding-ModUtil = "3.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
